# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  publish = ".next"
  command = "yarn build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.master.environment]
  BASE_URL = 'https://api.fortress.d.foundation/api/v1'
  GOOGLE_CLIENT_ID = '579303681879-lavu71osb0v5ko9nudn0p2dpppmbqjsb.apps.googleusercontent.com'
