name: Deploy - Development

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://develop--fortress-v2.netlify.app
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{github.event.after}}

      # https://gist.github.com/ffflorian/71de2e72a3788fbc63fa5ead8e3b5fde
      - name: Get Commit Message
        id: get_commit_message
        run: |
          MSG=$(git log --format=%B -n 1 ${{github.event.after}})
          echo "commit_message='$MSG'" >> $GITHUB_OUTPUT

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      # Cache node modules and next folder
      - name: Caching
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ${{ github.workspace }}/apps/admin/.next/cache
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      # Build & deploy the app
      - name: Build & Deploy
        id: build-and-deploy
        run: |
          COMMAND="netlify deploy --build -m ${{ steps.get_commit_message.outputs.commit_message }} --alias develop"
          OUTPUT=$(sh -c "$COMMAND")
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
